/**
 * SQLite database client (Drizzle + better-sqlite3).
 *
 * Single shared connection per process. The database file lives under
 * `data/nova.db` by default (mirroring the existing `data/` flat-file layout),
 * overridable via `NOVA_DB_PATH` for tests and Docker volume mounts.
 *
 * The schema is applied on first access via `migrate()` so deployments don't
 * need a separate migration step — but `drizzle-kit generate` is still used
 * during development to produce SQL migration files under `drizzle/` for
 * review and version control.
 */
import Database from 'better-sqlite3';
import { drizzle, type BetterSQLite3Database } from 'drizzle-orm/better-sqlite3';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import path from 'path';
import { createLogger } from '@/lib/logger';
import * as schema from './schema';

const log = createLogger('DB');

let _db: BetterSQLite3Database<typeof schema> | null = null;
let _sqlite: Database.Database | null = null;

export function resolveDbPath(): string {
  return process.env.NOVA_DB_PATH || path.join(process.cwd(), 'data', 'nova.db');
}

/**
 * Lazily initialize and return the shared Drizzle client.
 *
 * On first call this opens the SQLite file, enables WAL mode (concurrent
 * reads while writing — important for the SSE generation pipeline), and runs
 * pending migrations from `drizzle/`.
 *
 * Subsequent calls return the cached instance.
 */
export function getDb(): BetterSQLite3Database<typeof schema> {
  if (_db) return _db;

  const dbPath = resolveDbPath();
  log.info(`Opening SQLite database at ${dbPath}`);

  _sqlite = new Database(dbPath);
  // WAL mode for better read concurrency during generation jobs.
  _sqlite.pragma('journal_mode = WAL');
  _sqlite.pragma('foreign_keys = ON');

  _db = drizzle(_sqlite, { schema });

  // Run migrations. In production this is idempotent and fast (no-op if up
  // to date). The migrations folder is generated by `drizzle-kit generate`.
  try {
    const migrationsFolder = path.join(process.cwd(), 'drizzle');
    migrate(_db, { migrationsFolder });
    log.info('Database migrations applied');
  } catch (err) {
    // If the migrations folder doesn't exist yet (fresh checkout before the
    // first `drizzle-kit generate`), fall back to creating tables directly
    // from the schema so the app still boots.
    log.warn('Migration folder not found, creating schema directly:', err);
    createSchemaDirectly(_sqlite);
  }

  return _db;
}

/**
 * Fallback schema creation when migration files are absent.
 * This mirrors `lib/db/schema.ts` so a fresh checkout works without running
 * `drizzle-kit generate` first. Once migrations are committed, the
 * `migrate()` call above handles everything and this becomes a safety net.
 */
function createSchemaDirectly(sqlite: Database.Database): void {
  sqlite.exec(`
    CREATE TABLE IF NOT EXISTS users (
      id TEXT PRIMARY KEY,
      name TEXT,
      email TEXT NOT NULL UNIQUE,
      email_verified TEXT,
      image TEXT,
      password_hash TEXT,
      role TEXT NOT NULL DEFAULT 'user',
      disabled INTEGER NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
      updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    );

    CREATE TABLE IF NOT EXISTS accounts (
      user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      type TEXT NOT NULL,
      provider TEXT NOT NULL,
      provider_account_id TEXT NOT NULL,
      refresh_token TEXT,
      access_token TEXT,
      expires_at INTEGER,
      token_type TEXT,
      scope TEXT,
      id_token TEXT,
      session_state TEXT,
      PRIMARY KEY (provider, provider_account_id)
    );

    CREATE TABLE IF NOT EXISTS sessions (
      session_token TEXT PRIMARY KEY,
      user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      expires TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS verification_tokens (
      identifier TEXT NOT NULL,
      token TEXT NOT NULL,
      expires TEXT NOT NULL,
      PRIMARY KEY (identifier, token)
    );

    CREATE TABLE IF NOT EXISTS classrooms (
      id TEXT PRIMARY KEY,
      owner_id TEXT REFERENCES users(id) ON DELETE SET NULL,
      stage_json TEXT NOT NULL,
      scenes_json TEXT NOT NULL,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
      deleted INTEGER NOT NULL DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS skills (
      id TEXT PRIMARY KEY,
      owner_id TEXT REFERENCES users(id) ON DELETE SET NULL,
      display_name TEXT NOT NULL,
      category TEXT NOT NULL,
      summary TEXT NOT NULL,
      description TEXT NOT NULL,
      prompt_template TEXT NOT NULL,
      parameters_json TEXT NOT NULL DEFAULT '[]',
      enabled INTEGER NOT NULL DEFAULT 1,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    );

    CREATE TABLE IF NOT EXISTS usage_records (
      id TEXT PRIMARY KEY,
      created_at INTEGER NOT NULL,
      kind TEXT NOT NULL DEFAULT 'llm',
      source TEXT NOT NULL,
      provider_id TEXT NOT NULL,
      model_id TEXT NOT NULL,
      model_string TEXT NOT NULL,
      input_tokens INTEGER NOT NULL DEFAULT 0,
      output_tokens INTEGER NOT NULL DEFAULT 0,
      cache_read_tokens INTEGER NOT NULL DEFAULT 0,
      cache_creation_tokens INTEGER NOT NULL DEFAULT 0,
      reasoning_tokens INTEGER NOT NULL DEFAULT 0,
      quantity INTEGER,
      unit TEXT,
      user_id TEXT REFERENCES users(id) ON DELETE SET NULL
    );

    CREATE TABLE IF NOT EXISTS audit_logs (
      id TEXT PRIMARY KEY,
      created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
      actor_id TEXT,
      actor_role TEXT,
      action TEXT NOT NULL,
      entity_type TEXT,
      entity_id TEXT,
      details_json TEXT,
      ip_address TEXT,
      user_agent TEXT
    );

    CREATE TABLE IF NOT EXISTS api_keys (
      id TEXT PRIMARY KEY,
      owner_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      label TEXT NOT NULL,
      key_hash TEXT NOT NULL UNIQUE,
      key_prefix TEXT NOT NULL,
      scopes TEXT NOT NULL DEFAULT '[]',
      last_used_at TEXT,
      expires_at TEXT,
      created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
      revoked_at TEXT
    );

    CREATE INDEX IF NOT EXISTS idx_classrooms_owner ON classrooms(owner_id);
    CREATE INDEX IF NOT EXISTS idx_classrooms_created ON classrooms(created_at);
    CREATE INDEX IF NOT EXISTS idx_skills_owner ON skills(owner_id);
    CREATE INDEX IF NOT EXISTS idx_usage_created ON usage_records(created_at);
    CREATE INDEX IF NOT EXISTS idx_usage_user ON usage_records(user_id);
    CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at);
    CREATE INDEX IF NOT EXISTS idx_audit_actor ON audit_logs(actor_id);
    CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_logs(entity_type, entity_id);
    CREATE INDEX IF NOT EXISTS idx_api_keys_owner ON api_keys(owner_id);
    CREATE INDEX IF NOT EXISTS idx_api_keys_hash ON api_keys(key_hash);
  `);
  log.info('Schema created directly (fallback path)');
}

/**
 * Close the database connection. Intended for tests and graceful shutdown.
 */
export function closeDb(): void {
  if (_sqlite) {
    _sqlite.close();
    _sqlite = null;
    _db = null;
  }
}

/**
 * Reset the database state entirely. TESTS ONLY — deletes the on-disk file
 * content by reinitializing. Callers in production should use migrations.
 */
export function resetDbForTests(): void {
  closeDb();
}
