/**
 * Inter-agent messaging layer.
 *
 * Background: an audit found that agents in the Nova classroom never
 * communicate with each other directly — every interaction is implicit via
 * prompt-context injection (see `summarizers/peer-context.ts`). This module
 * provides an *explicit* messaging layer so agents can send, broadcast, and
 * hand off structured messages to peers.
 *
 * Design:
 *  - `AgentMessageBus` is an in-memory, per-session instance (NOT a global
 *    singleton). One bus is created per classroom session via the
 *    `message-bus-manager` and discarded when the session ends.
 *  - Messages are append-only. `receive()` returns unread messages for an
 *    agent and marks them as read; `getHistory()` is a non-destructive read.
 *  - Three message types: `direct` (one-to-one), `broadcast` (one-to-all),
 *    and `handoff` (structured context transfer between agents).
 *
 * Persistence: v1 uses an in-memory array scoped to a session. For
 * multi-instance deployments this should be backed by Redis or the database;
 * the interface is designed to make that swap straightforward (mirroring the
 * approval-workflow module).
 */
import { createLogger } from '@/lib/logger';

const log = createLogger('AgentMessaging');

// ─── Types ──────────────────────────────────────────────────────────────────

/**
 * The recipient of a message — either a specific agent ID or the literal
 * `'broadcast'` sentinel indicating all agents.
 */
export type MessageRecipient = string | 'broadcast';

/**
 * The kind of inter-agent message.
 *  - `direct`    — one agent sends a message to one specific peer.
 *  - `broadcast` — one agent sends a message to every agent in the session.
 *  - `handoff`   — a structured context transfer from one agent to another,
 *                   typically used when responsibility for a task moves.
 */
export type MessageType = 'direct' | 'broadcast' | 'handoff';

/**
 * A single message exchanged between agents.
 */
export interface AgentMessage {
  /** Unique ID for this message (generated by the bus). */
  id: string;
  /** The ID of the agent that sent the message. */
  fromAgentId: string;
  /** The recipient agent ID, or `'broadcast'` for all agents. */
  toAgentId: MessageRecipient;
  /** The message body. */
  content: string;
  /** Epoch milliseconds — when the message was created. */
  timestamp: number;
  /** The semantic type of the message. */
  messageType: MessageType;
  /** Optional structured metadata (e.g. handoff context, tags, priority). */
  metadata?: Record<string, unknown>;
}

/**
 * The input shape for `send()` — everything except the auto-generated
 * `id` and `timestamp` fields.
 */
export type SendableMessage = Omit<AgentMessage, 'id' | 'timestamp'>;

// ─── Helpers ────────────────────────────────────────────────────────────────

/**
 * Generate a unique message ID.
 * Format: `msg_<base36-timestamp>_<random>`.
 */
function generateMessageId(): string {
  return `msg_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
}

// ─── AgentMessageBus ────────────────────────────────────────────────────────

/**
 * In-memory message bus for a single classroom session.
 *
 * Each instance is created per-session by the `message-bus-manager` and is
 * NOT shared across sessions. Messages are stored in an append-only array;
 * read state is tracked per (message, agent) pair so that broadcast messages
 * are only marked read for the agent that consumed them.
 */
export class AgentMessageBus {
  /** Append-only log of every message sent through this bus. */
  private readonly messages: AgentMessage[] = [];

  /**
   * Read receipts keyed by message ID. The set holds every agent ID that has
   * already consumed (received) that message. This lets a broadcast message
   * be "unread" for agent B even after agent A has received it.
   */
  private readonly readReceipts: Map<string, Set<string>> = new Map();

  /** The session this bus belongs to (for logging context). */
  private readonly sessionId: string;

  constructor(sessionId: string) {
    this.sessionId = sessionId;
  }

  /**
   * Send a message through the bus.
   *
   * The caller supplies everything except `id` and `timestamp`, which are
   * generated here. The message type is taken from the payload — callers
   * sending a broadcast should set `toAgentId: 'broadcast'` and
   * `messageType: 'broadcast'` (the `broadcast()` convenience method does
   * this automatically).
   *
   * @returns the fully-formed `AgentMessage` (with id + timestamp).
   */
  send(message: SendableMessage): AgentMessage {
    const fullMessage: AgentMessage = {
      ...message,
      id: generateMessageId(),
      timestamp: Date.now(),
    };

    this.messages.push(fullMessage);
    // Initialise an empty read-receipt set so the message is unread for all.
    this.readReceipts.set(fullMessage.id, new Set());

    log.debug('Message sent', {
      sessionId: this.sessionId,
      messageId: fullMessage.id,
      from: fullMessage.fromAgentId,
      to: fullMessage.toAgentId,
      type: fullMessage.messageType,
    });

    return fullMessage;
  }

  /**
   * Receive (consume) all unread messages addressed to an agent.
   *
   * A message is considered "for" an agent when:
   *  - it is a direct/handoff message whose `toAgentId` matches, OR
   *  - it is a broadcast message and the agent is not the sender.
   *
   * Returned messages are marked as read for this agent so subsequent calls
   * do not return them again. The original sender never receives its own
   * messages.
   *
   * @returns the unread messages for `agentId` (oldest first), now marked read.
   */
  receive(agentId: string): AgentMessage[] {
    const unread: AgentMessage[] = [];

    for (const message of this.messages) {
      // An agent never receives its own messages.
      if (message.fromAgentId === agentId) continue;

      const isAddressedToAgent = this.isForAgent(message, agentId);
      if (!isAddressedToAgent) continue;

      const readers = this.readReceipts.get(message.id);
      if (readers && readers.has(agentId)) continue; // already read

      unread.push(message);
    }

    // Mark them as read.
    for (const message of unread) {
      const readers = this.readReceipts.get(message.id);
      if (readers) {
        readers.add(agentId);
      }
    }

    if (unread.length > 0) {
      log.debug('Messages received', {
        sessionId: this.sessionId,
        agentId,
        count: unread.length,
      });
    }

    return unread;
  }

  /**
   * Broadcast a message to every agent in the session.
   *
   * Convenience wrapper around `send()` that sets `toAgentId: 'broadcast'`
   * and `messageType: 'broadcast'`.
   *
   * @returns the fully-formed broadcast `AgentMessage`.
   */
  broadcast(
    fromAgentId: string,
    content: string,
    metadata?: Record<string, unknown>,
  ): AgentMessage {
    return this.send({
      fromAgentId,
      toAgentId: 'broadcast',
      content,
      messageType: 'broadcast',
      metadata,
    });
  }

  /**
   * Perform a structured handoff from one agent to another.
   *
   * A handoff transfers responsibility (and optional context via `metadata`)
   * from `fromAgentId` to `toAgentId`. The `metadata` field is the natural
   * place to carry the context being transferred — e.g. a summary of work
   * done so far, relevant state pointers, or a task description.
   *
   * @returns the fully-formed handoff `AgentMessage`.
   */
  handoff(
    fromAgentId: string,
    toAgentId: string,
    content: string,
    metadata?: Record<string, unknown>,
  ): AgentMessage {
    return this.send({
      fromAgentId,
      toAgentId,
      content,
      messageType: 'handoff',
      metadata,
    });
  }

  /**
   * Get the message history — non-destructive (does NOT mark as read).
   *
   * @param agentId - When provided, returns only messages where the agent is
   *                  the sender or an addressed recipient (direct/handoff to
   *                  them, or any broadcast). When omitted, returns every
   *                  message on the bus.
   * @returns messages oldest-first.
   */
  getHistory(agentId?: string): AgentMessage[] {
    if (!agentId) return [...this.messages];

    return this.messages.filter(
      (m) =>
        m.fromAgentId === agentId ||
        this.isForAgent(m, agentId),
    );
  }

  /**
   * Clear all messages and read receipts from the bus.
   */
  clear(): void {
    const count = this.messages.length;
    this.messages.length = 0;
    this.readReceipts.clear();
    log.debug('Message bus cleared', {
      sessionId: this.sessionId,
      clearedCount: count,
    });
  }

  // ─── Internal helpers ──────────────────────────────────────────────────

  /**
   * Whether a message is addressed to a given agent (ignoring read state).
   *  - direct / handoff: exact `toAgentId` match.
   *  - broadcast: addressed to everyone (the sender check is handled by the
   *    caller, so this returns true for any non-sender agent).
   */
  private isForAgent(message: AgentMessage, agentId: string): boolean {
    if (message.messageType === 'broadcast' || message.toAgentId === 'broadcast') {
      return true;
    }
    return message.toAgentId === agentId;
  }
}
