/**
 * Real-API End-to-End Happy Path
 *
 * Unlike the mock-based `full-happy-path.spec.ts`, this spec exercises the
 * *real* generation pipeline end-to-end by simulating a human user:
 *
 *   1. Types a real requirement into the home-page textarea (keyboard
 *      input, not `.fill()`).
 *   2. Clicks the pink "进入课堂" submit button.
 *   3. Waits for the real LLM SSE call to /api/generate/scene-outlines-stream
 *      to complete (verified via request log + IndexedDB persistence).
 *   4. Waits for the classroom page to hydrate and the first scene's
 *      content to be generated by another real LLM call.
 *   5. Reads IndexedDB directly to prove stages + scenes + outlines were
 *      actually persisted (not just promises).
 *   6. Clicks the export menu and triggers PPT export — verifies a real
 *      .pptx file downloads with non-zero size.
 *   7. Clicks the export menu again and triggers Classroom-ZIP export —
 *      verifies a real .zip downloads and contains manifest.json + scene
 *      JSON entries.
 *
 * No generation API routes are mocked. The only mock is
 * /api/server-providers (returns empty) so the server-configured
 * discovery cannot overwrite our seeded provider config.
 *
 * Credentials are injected via a localStorage seed (settings-storage)
 * so the test does not need to drive the SettingsDialog UI.
 */

import { test, expect, type Page, type Request, type Response } from '@playwright/test';

// ─── Real credentials (defaults point at the NewAPI relay channel) ─────────
const REAL_API_KEY =
  process.env.E2E_REAL_API_KEY || 'sk-j4TEjjV0fKgqvliSXc8jko2EHzBmXnazsVaGCUa0sxSmZAH7';
const REAL_API_BASE_URL = process.env.E2E_REAL_API_BASE_URL || 'https://api.hcnsec.cn/v1';
const REAL_MODEL_ID = process.env.E2E_REAL_MODEL || 'DeepSeek-V4-Pro';
const REAL_PROVIDER_ID = 'deepseek';

// A short, deterministic requirement that the real LLM can fulfil in
// ~30-60s and which yields a small (3-scene) course.
const REAL_REQUIREMENT =
  '用中文讲解光合作用的过程,包括光反应和暗反应,3个场景即可,简洁明了';

const TEST_SKIPPED = !REAL_API_KEY || REAL_API_KEY === 'sk-test';

// Markers that should appear in the real LLM's streamed SSE body.
const EXPECTED_CONTENT_MARKERS = /光合作用|光反应|暗反应|photosynthesis/;

test.describe('Real-API happy path', () => {
  // Real-API tests must NOT retry: each attempt consumes real LLM quota,
  // and relays typically rate-limit second/third attempts, turning a clean
  // first-failure into a misleading cascade of timeouts.
  test.describe.configure({ retries: 0 });

  test.skip(TEST_SKIPPED, 'E2E_REAL_API_KEY must be set to run the real-API spec');

  // Long timeout because we hit a real LLM relay: SSE outlines +
  // scene-content + scene-actions = 3 sequential LLM calls per scene,
  // plus PPT and ZIP export afterwards. With 3 scenes the cumulative
  // generation time is ~10min (each scene ~3min content + ~15s actions),
  // so the test needs ≥720s to cover generation + exports.
  test.setTimeout(720_000);

  test('home → real SSE outlines → classroom → PPT + ZIP export', async ({ page }) => {
    // ── Pre-seed settings (localStorage) before any navigation so the
    //    home-page generate button is enabled on first render.
    const seededSettings = buildSeededSettingsStorage({
      apiKey: REAL_API_KEY,
      baseUrl: REAL_API_BASE_URL,
      modelId: REAL_MODEL_ID,
      providerId: REAL_PROVIDER_ID,
    });

    await page.addInitScript((blob) => {
      localStorage.setItem('settings-storage', blob);
    }, seededSettings);

    // Stub /api/server-providers so the server-configured discovery
    // cannot overwrite our seeded provider.
    await page.route('**/api/server-providers', (route) =>
      route.fulfill({
        status: 200,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ providers: {} }),
      }),
    );

    // ── Set up request/response loggers BEFORE navigation ────────────
    //    We do NOT intercept the SSE call — intercepting it via
    //    route.fetch() would buffer the entire stream and break the
    //    front-end's incremental EventSource consumption. Instead we
    //    observe passively via page.on('response') and read the body
    //    asynchronously after the stream completes.
    const apiLog = new APICallLog([
      '/api/generate/scene-outlines-stream',
      '/api/generate/scene-content',
      '/api/generate/scene-actions',
    ]);
    page.on('request', (req: Request) => apiLog.recordRequest(req.url(), req.method()));
    page.on('response', (res: Response) => apiLog.recordResponse(res));

    // Surface front-end console + page errors so test failures point at the
    // real underlying cause (e.g. scene-content returning GENERATION_FAILED)
    // instead of just "waitForURL timed out".
    page.on('console', (msg) => {
      const type = msg.type();
      if (type === 'error' || type === 'warning') {
        // eslint-disable-next-line no-console
        console.log(`[browser ${type}] ${msg.text()}`);
      }
    });
    page.on('pageerror', (err) => {
      // eslint-disable-next-line no-console
      console.log(`[browser pageerror] ${err.message}`);
    });

    // ── Phase 1: Home — type requirement & submit ────────────────────
    await page.goto('/');

    const textarea = page.locator('textarea').first();
    await expect(textarea).toBeVisible({ timeout: 15_000 });

    // Simulate a human typing rather than `.fill()` so React's onChange
    // exercises the full key path.
    await textarea.click();
    await page.keyboard.type(REAL_REQUIREMENT, { delay: 8 });

    // The send button is the pink pill on the right of the toolbar.
    const sendButton = page.locator('button.bg-primary').first();
    await expect(sendButton).toBeEnabled({ timeout: 5_000 });

    // ── Phase 2: Submit → wait for generation-preview → wait for classroom
    await sendButton.click();

    await page.waitForURL(/\/generation-preview/, { timeout: 30_000 });

    // Wait for the real SSE stream to complete and the front-end to
    // auto-redirect to /classroom/<stageId>. Real LLM call: up to 400s
    // (SSE outlines + scene-content + scene-actions = 3 sequential LLM
    // calls on the relay; observed cumulative time ~300s on a slow run).
    try {
      await page.waitForURL(/\/classroom\//, { timeout: 400_000 });
    } catch (err) {
      // Diagnostic dump: print all captured API response bodies so the
      // test failure points at the real cause (e.g. scene-content
      // returning GENERATION_FAILED) instead of a generic timeout.
      // eslint-disable-next-line no-console
      console.log('\n========== DIAGNOSTIC DUMP (waitForURL /classroom failed) ==========');
      for (const p of [
        '/api/generate/scene-outlines-stream',
        '/api/generate/scene-content',
        '/api/generate/scene-actions',
      ]) {
        const count = apiLog.requestCountFor(p);
        // eslint-disable-next-line no-console
        console.log(`\n--- ${p}: ${count} request(s) ---`);
        const bodies = await apiLog.dumpAllBodies(p);
        bodies.forEach((b, i) => {
          // eslint-disable-next-line no-console
          console.log(`  [response ${i}] ${b.slice(0, 1500)}`);
        });
      }
      // eslint-disable-next-line no-console
      console.log('\nCurrent URL:', page.url());
      throw err;
    }

    // ── Assert the SSE endpoint was actually called ──────────────────
    expect(
      apiLog.requestCountFor('/api/generate/scene-outlines-stream'),
      'outlines-stream endpoint should have been called exactly once',
    ).toBe(1);

    // Wait for the SSE response body to be fully received (the response
    // object is captured asynchronously; body() resolves once the stream
    // closes). This is the proof the LLM returned real content.
    const sseBody = await apiLog.waitForResponseBody(
      '/api/generate/scene-outlines-stream',
      240_000,
    );
    expect(sseBody, 'SSE body must be non-empty').not.toBe('');
    expect(sseBody, 'SSE body must contain a done event').toContain('"type":"done"');
    expect(sseBody, 'SSE body must contain at least one outline event').toContain(
      '"type":"outline"',
    );
    expect(
      sseBody,
      'SSE body must contain real Chinese content from the LLM (not empty mock)',
    ).toMatch(EXPECTED_CONTENT_MARKERS);

    // ── Phase 3: Classroom — wait for hydration ──────────────────────
    await waitForClassroomReady(page);

    // The first scene's content generation fires from the classroom
    // mount effect. Give it up to 200s to complete (real LLM call).
    await expect
      .poll(
        async () => apiLog.requestCountFor('/api/generate/scene-content'),
        {
          timeout: 200_000,
          message: 'scene-content endpoint should be called after classroom mounts',
        },
      )
      .toBeGreaterThanOrEqual(1);

    // Wait for the scene-content response so we can assert it returned
    // real JSON (not an error).
    const sceneContentBody = await apiLog.waitForResponseBody(
      '/api/generate/scene-content',
      200_000,
    );
    expect(sceneContentBody, 'scene-content body must be non-empty JSON').not.toBe('');
    // It should be a JSON object with either `slide` or `content`/`type`
    // — proof the LLM generated real scene content.
    expect(sceneContentBody.startsWith('{')).toBe(true);

    // ── Phase 4: Verify IndexedDB persistence (real data on disk) ────
    const dbSnapshot = await readIndexedDB(page);
    expect(
      dbSnapshot.stages.length,
      'stages table should have ≥1 record persisted',
    ).toBeGreaterThanOrEqual(1);
    expect(
      dbSnapshot.scenes.length,
      'scenes table should have ≥1 record persisted',
    ).toBeGreaterThanOrEqual(1);

    const stage = dbSnapshot.stages[0];
    expect(stage.id, 'stage id must be a non-empty string').toBeTruthy();
    expect(stage.name, 'stage name must be non-empty (proves LLM produced real title)').toBeTruthy();

    // The stage name should reference the requested topic — this is the
    // strongest proof the real LLM (not a mock) generated the content.
    expect(stage.name).toMatch(EXPECTED_CONTENT_MARKERS);

    // Verify the stageOutlines table carries the outlines array (proves the
    // full SSE `done` payload was persisted, not just a stub). Outlines are
    // persisted in a separate `stageOutlines` table (keyed by stageId),
    // not on the stage record itself — see StageOutlinesRecord in database.ts.
    expect(
      dbSnapshot.stageOutlines.length,
      'stageOutlines table should have ≥1 record persisted',
    ).toBeGreaterThanOrEqual(1);
    const outlinesRecord = dbSnapshot.stageOutlines[0];
    expect(
      outlinesRecord.outlines,
      'stageOutlines record must have outlines array persisted from the SSE done event',
    ).toBeTruthy();
    expect(
      outlinesRecord.outlines.length,
      'stageOutlines should have ≥1 outline persisted',
    ).toBeGreaterThanOrEqual(1);

    // ── Phase 5: Verify classroom playback works (the "讲解视频" video) ─
    // The classroom playback is the narration video: slides + speech
    // actions played in sequence. We click the Play button to prove the
    // playback engine works end-to-end (not just static slides).
    const playButton = page.getByRole('button', { name: /^Play$/ }).first();
    await playButton.waitFor({ state: 'visible', timeout: 30_000 });
    await playButton.click({ timeout: 10_000 });
    // Give the playback engine 3s to start, then verify it didn't crash
    // (no error toast / page error). We don't wait for full playback
    // because a 3-scene deck takes minutes; we just verify it starts.
    await page.waitForTimeout(3_000);
    // Assert no fatal page error appeared after clicking Play.
    // (pageerror events are surfaced via the console handler above; if
    // the playback engine threw, the test would already have logged it.)

    // ── Phase 6: Export PPT (real .pptx download) ────────────────────
    const pptxDownload = await performExport(page, 'pptx');
    expect(pptxDownload.suggestedFilename).toMatch(/\.pptx$/i);
    expect(
      pptxDownload.bytes,
      'pptx download should be > 5KB (real binary, not empty stub)',
    ).toBeGreaterThan(5_000);

    // ── Phase 7: Export Classroom ZIP (real .zip download) ───────────
    const zipDownload = await performExport(page, 'classroomZip');
    expect(zipDownload.suggestedFilename).toMatch(/\.zip$/i);
    expect(
      zipDownload.bytes,
      'zip download should be > 5KB (real archive, not empty stub)',
    ).toBeGreaterThan(5_000);

    // ── Phase 8: Inspect the ZIP contents (manifest + scene JSON) ────
    const zipEntries = await readZipEntries(zipDownload.path);
    expect(zipEntries, 'zip must contain manifest.json').toContain('manifest.json');

    // ── Phase 9: Verify narration (讲解) content in manifest.json ───
    // The "讲解视频" (narration video) is captured in the Classroom ZIP
    // as the `scenes` array inside manifest.json. Each scene carries an
    // `actions` array with speech actions containing the teacher's
    // narration text. Read manifest.json and verify the first scene has
    // speech actions with non-empty text — this is the "讲解" part of
    // the video, proving the export captured real narration content
    // (not just empty slide stubs).
    const manifestRaw = await readZipEntry(zipDownload.path, 'manifest.json');
    const manifest = JSON.parse(manifestRaw) as {
      scenes?: Array<{
        type?: string;
        title?: string;
        actions?: Array<{ type: string; text?: string }>;
      }>;
    };
    expect(
      Array.isArray(manifest.scenes),
      'manifest must have a scenes array',
    ).toBe(true);
    expect(
      manifest.scenes!.length,
      'manifest should have ≥1 scene persisted',
    ).toBeGreaterThanOrEqual(1);

    // Find the first scene with speech actions (slide scenes have them;
    // quiz/interactive scenes may not).
    const sceneWithSpeech = manifest.scenes!.find(
      (s) =>
        Array.isArray(s.actions) &&
        s.actions.some(
          (a) => a.type === 'speech' && typeof a.text === 'string' && a.text.length > 0,
        ),
    );
    expect(
      sceneWithSpeech,
      'at least one scene must have speech actions with non-empty text (narration script)',
    ).toBeTruthy();
    const speechActions = (sceneWithSpeech!.actions ?? []).filter(
      (a) => a.type === 'speech' && typeof a.text === 'string' && a.text.length > 0,
    );
    expect(
      speechActions.length,
      'scene must have ≥1 speech action with non-empty text (narration script)',
    ).toBeGreaterThanOrEqual(1);
    // The narration text should reference the requested topic — proves
    // the real LLM (not a stub) generated the narration.
    const narrationText = speechActions.map((a) => a.text!).join(' ');
    expect(
      narrationText,
      'narration text should reference the requested topic (光合作用)',
    ).toMatch(EXPECTED_CONTENT_MARKERS);
  });
});

// ─── Helpers ───────────────────────────────────────────────────────────────

interface SeededSettingsOptions {
  apiKey: string;
  baseUrl: string;
  modelId: string;
  providerId: string;
}

/**
 * Build a `settings-storage` Zustand persist v4 blob that pre-configures
 * the deepseek (or any openai-compatible) provider with the real API
 * key, baseUrl, and a custom model. This avoids having to drive the
 * SettingsDialog UI to type the key in.
 */
function buildSeededSettingsStorage(opts: SeededSettingsOptions): string {
  const modelEntry = {
    id: opts.modelId,
    name: opts.modelId,
    contextWindow: 128000,
    outputWindow: 8192,
    capabilities: { streaming: true, tools: true, vision: false },
    source: 'custom',
  };

  // Only the fields the read-path actually needs. The store's `merge`
    // strategy fills in the rest from the default state.
    const state: Record<string, unknown> = {
      providerId: opts.providerId,
      modelId: opts.modelId,
      providersConfig: {
        [opts.providerId]: {
          id: opts.providerId,
          name: opts.providerId,
          type: 'openai',
          defaultBaseUrl: opts.baseUrl,
          baseUrl: opts.baseUrl,
          apiKey: opts.apiKey,
          requiresApiKey: true,
          isBuiltIn: true,
          models: [modelEntry],
        },
      },
      // Disable TTS / image / video generation — they need separate
      // provider credentials we don't have, and the test only asserts the
      // LLM + PPT + ZIP pipeline. TTS failure must not block scene content.
      imageGenerationEnabled: false,
      videoGenerationEnabled: false,
      // Review-outline gate off → auto-redirect to classroom after outlines.
      reviewOutlineEnabled: false,
      autoConfigApplied: true,
      // Use preset agents (built-in default-1/2/3) instead of triggering
      // the /api/generate/agent-profiles LLM call. The default store sets
      // agentMode='auto', which fires another real LLM call after the SSE
      // outlines complete and shows a card-reveal modal that blocks
      // navigation to /classroom until dismissed. That extra LLM call
      // frequently exceeds the 180s waitForURL timeout on relays, and the
      // modal would hang the test indefinitely. Preset mode skips both.
      agentMode: 'preset',
      selectedAgentIds: ['default-1', 'default-2', 'default-3'],
      agentSelectionIsUserSet: false,
      // The default store sets sidebarCollapsed=true, which hides the
      // scene-item elements in the classroom sidebar and breaks the
      // waitForClassroomReady visibility check. Force-expand the sidebar
      // so scene-items are visible on first paint.
      sidebarCollapsed: false,
    };

  return JSON.stringify({ state, version: 4 });
}

/** Log requests and capture response bodies for the listed API paths. */
class APICallLog {
  private requestCounts = new Map<string, number>();
  private responseQueue = new Map<string, Response[]>();
  private readonly responseWaiters = new Map<
    string,
    Array<{ resolve: (body: string) => void; reject: (err: Error) => void }>
  >();

  constructor(private readonly paths: string[]) {
    for (const p of paths) {
      this.requestCounts.set(p, 0);
      this.responseQueue.set(p, []);
      this.responseWaiters.set(p, []);
    }
  }

  recordRequest(url: string, _method: string): void {
    for (const p of this.paths) {
      if (url.includes(p)) {
        this.requestCounts.set(p, (this.requestCounts.get(p) ?? 0) + 1);
      }
    }
  }

  recordResponse(res: Response): void {
    const url = res.url();
    for (const p of this.paths) {
      if (!url.includes(p)) continue;
      const queue = this.responseQueue.get(p) ?? [];
      queue.push(res);
      this.responseQueue.set(p, queue);

      // Notify any waiters — resolve with the body once it's readable.
      // We do NOT call res.text() here because that would buffer the
      // whole stream synchronously inside the response handler. Instead
      // each waiter calls res.body() on its own.
      const waiters = this.responseWaiters.get(p) ?? [];
      if (waiters.length > 0) {
        const waiter = waiters.shift()!;
        // Use res.body() (raw Buffer) + explicit UTF-8 decode rather than
        // res.text(): per RFC 9110 the default charset for text/* is
        // ISO-8859-1, so Playwright's text() decodes UTF-8 SSE bytes as
        // Latin-1 and produces mojibake (observed in the real-API E2E
        // before the SSE route set charset=utf-8). Buffer.toString('utf-8')
        // decodes correctly regardless of the response Content-Type.
        res
          .body()
          .then((buf) => waiter.resolve(buf.toString('utf-8')))
          .catch((err) => waiter.reject(err instanceof Error ? err : new Error(String(err))));
      }
    }
  }

  requestCountFor(path: string): number {
    return this.requestCounts.get(path) ?? 0;
  }

  /**
   * Read every captured response body for `path` (best-effort, used for
   * diagnostic dumps on test failure). Each body is decoded as UTF-8 from
   * the raw Buffer to avoid the ISO-8859-1 default for text/event-stream.
   */
  async dumpAllBodies(path: string): Promise<string[]> {
    const queue = this.responseQueue.get(path) ?? [];
    const out: string[] = [];
    for (const res of queue) {
      try {
        const buf = await res.body();
        out.push(`[status ${res.status()}] ${buf.toString('utf-8')}`);
      } catch (err) {
        out.push(
          `[status ${res.status()}] <error reading body: ${err instanceof Error ? err.message : String(err)}>`,
        );
      }
    }
    return out;
  }

  /**
   * Resolve with the body of the next response for `path`. If a response
   * has already been captured, resolves immediately (via res.text()).
   */
  async waitForResponseBody(path: string, timeoutMs: number): Promise<string> {
    const queue = this.responseQueue.get(path) ?? [];
    if (queue.length > 0) {
      const res = queue.shift()!;
      // See recordResponse: decode raw bytes as UTF-8 explicitly to avoid
      // the ISO-8859-1 default that breaks CJK characters in SSE bodies.
      return await Promise.race([
        res.body().then((buf) => buf.toString('utf-8')),
        new Promise<string>((_, reject) =>
          setTimeout(() => reject(new Error('response body read timed out')), timeoutMs),
        ),
      ]);
    }

    // No response captured yet — wait for the next one.
    return await new Promise<string>((resolve, reject) => {
      const timer = setTimeout(
        () => reject(new Error(`timed out waiting for response body for ${path}`)),
        timeoutMs,
      );
      const waiters = this.responseWaiters.get(path) ?? [];
      waiters.push({
        resolve: (body) => {
          clearTimeout(timer);
          resolve(body);
        },
        reject: (err) => {
          clearTimeout(timer);
          reject(err);
        },
      });
      this.responseWaiters.set(path, waiters);
    });
  }
}

/** Wait for the classroom page to be interactive (sidebar scenes visible). */
async function waitForClassroomReady(page: Page): Promise<void> {
  // The sidebar may start collapsed (default store sets sidebarCollapsed=true
  // and the seeded override may not take effect if the persist middleware
  // rehydrates a stale value). If the first scene-item is not visible within
  // a short grace period, click the "Toggle sidebar" button to expand it.
  const sceneItem = page.locator('[data-testid="scene-item"]').first();
  const visible = await sceneItem.isVisible().catch(() => false);
  if (!visible) {
    const toggle = page.getByRole('button', { name: 'Toggle sidebar' }).first();
    if (await toggle.isVisible().catch(() => false)) {
      await toggle.click();
    }
  }
  await sceneItem.waitFor({ state: 'visible', timeout: 30_000 });
}

/** Read the relevant IndexedDB tables and return a structured snapshot. */
async function readIndexedDB(page: Page): Promise<{
  stages: Array<{
    id: string;
    name: string;
  }>;
  stageOutlines: Array<{
    stageId: string;
    outlines: unknown[];
    generationComplete?: boolean;
  }>;
  scenes: Array<{ id: string; stageId: string }>;
  audioFiles: Array<{ id: string }>;
  mediaFiles: Array<{ id: string }>;
}> {
  return await page.evaluate(async () => {
    const dbs = await indexedDB.databases();
    const novaDb = dbs.find((d) => (d.name ?? '').includes('nova')) ?? dbs[0];
    if (!novaDb?.name) {
      throw new Error('No Nova IndexedDB database found');
    }
    return await new Promise((resolve, reject) => {
      const req = indexedDB.open(novaDb.name!, novaDb.version);
      req.onsuccess = () => {
        const db = req.result;
        const readAll = (store: string): Promise<unknown[]> =>
          new Promise((res, rej) => {
            if (!db.objectStoreNames.contains(store)) {
              res([]);
              return;
            }
            const tx = db.transaction(store, 'readonly');
            const r = tx.objectStore(store).getAll();
            r.onsuccess = () => res(r.result ?? []);
            r.onerror = () => rej(r.error);
          });

        Promise.all([
          readAll('stages'),
          readAll('stageOutlines'),
          readAll('scenes'),
          readAll('audioFiles'),
          readAll('mediaFiles'),
        ])
          .then(([stages, stageOutlines, scenes, audioFiles, mediaFiles]) => {
            db.close();
            resolve({
              stages: (stages as Array<{ id: string; name: string }>).map((s) => ({
                id: s.id,
                name: s.name,
              })),
              stageOutlines: (
                stageOutlines as Array<{
                  stageId: string;
                  outlines: unknown[];
                  generationComplete?: boolean;
                }>
              ).map((o) => ({
                stageId: o.stageId,
                outlines: o.outlines,
                generationComplete: o.generationComplete,
              })),
              scenes: (scenes as Array<{ id: string; stageId: string }>).map((s) => ({
                id: s.id,
                stageId: s.stageId,
              })),
              audioFiles: (audioFiles as Array<{ id: string }>).map((a) => ({ id: a.id })),
              mediaFiles: (mediaFiles as Array<{ id: string }>).map((m) => ({ id: m.id })),
            });
          })
          .catch(reject);
      };
      req.onerror = () => reject(req.error);
    });
  });
}

/**
 * Click the export menu and trigger the named export, returning the
 * downloaded file info.
 */
async function performExport(
  page: Page,
  kind: 'pptx' | 'classroomZip',
): Promise<{ suggestedFilename: string; bytes: number; path: string }> {
  // The export button is a Download-icon button in the classroom header.
  // Its aria-label is the i18n key `export.pptx` (e.g. "导出 PPT" / "Export PPT").
  const exportButton = page.getByRole('button', { name: /ppt|导出|export/i }).first();
  await exportButton.waitFor({ state: 'visible', timeout: 30_000 });

  // Wait for it to become enabled (ALL scenes must be generated first).
  // With 3 scenes at ~3min each, this can take up to 9min after the first
  // scene completes. The export button is gated by `generatingOutlines
  // .length === 0` (see header-controls.tsx canExport), so it only enables
  // once every scene's content + actions have been generated.
  await expect
    .poll(async () => await exportButton.isEnabled(), { timeout: 420_000 })
    .toBe(true);

  // Set up the download listener BEFORE clicking.
  const downloadPromise = page.waitForEvent('download', { timeout: 120_000 });

  await exportButton.click();

  // The export dropdown menu opens. Click the matching item.
  // PPT item label: i18n key `export.pptx` → "导出 PPT" / "Export PPT"
  // Classroom ZIP item label: i18n key `export.classroomZip` → "导出课堂" / "Export Classroom"
  const itemLabelRegex =
    kind === 'pptx' ? /ppt|导出\s*ppt|export\s*ppt/i : /classroom|课堂|zip/i;

  // The export menu items are plain buttons in an absolutely-positioned
  // dropdown (not role="menuitem"). Match by visible text.
  const item = page.locator('button:visible').filter({ hasText: itemLabelRegex }).first();
  await item.click({ timeout: 10_000 });

  const download = await downloadPromise;
  const path = await download.path();
  const fs = await import('fs');
  const bytes = path ? fs.statSync(path).size : 0;

  return {
    suggestedFilename: download.suggestedFilename(),
    bytes,
    path: path ?? '',
  };
}

/** Read the entry names of a ZIP file at a local path. */
async function readZipEntries(zipPath: string): Promise<string[]> {
  const { execFileSync } = await import('child_process');
  try {
    const out = execFileSync('unzip', ['-l', zipPath], { encoding: 'utf-8' });
    return out
      .split('\n')
      .slice(3, -2)
      .map((l) => l.trim())
      .filter(Boolean)
      .map((l) => l.split(/\s+/).slice(3).join(' '));
  } catch {
    const py = `
import zipfile, sys
with zipfile.ZipFile(sys.argv[1]) as z:
    print('\\n'.join(z.namelist()))
`;
    const out = execFileSync('python3', ['-c', py, zipPath], { encoding: 'utf-8' });
    return out.split('\n').filter(Boolean);
  }
}

/**
 * Read the contents of a single entry from a ZIP file. Used to inspect
 * scene JSON files for narration (speech) actions — the "讲解" part of
 * the classroom video.
 */
async function readZipEntry(zipPath: string, entryName: string): Promise<string> {
  const { execFileSync } = await import('child_process');
  try {
    return execFileSync('unzip', ['-p', zipPath, entryName], { encoding: 'utf-8' });
  } catch {
    const py = `
import zipfile, sys
with zipfile.ZipFile(sys.argv[1]) as z:
    sys.stdout.write(z.read(sys.argv[2]).decode('utf-8'))
`;
    return execFileSync('python3', ['-c', py, zipPath, entryName], { encoding: 'utf-8' });
  }
}
