// Pre-generated cached demo course for instant loading
// This is a complete "Artificial Intelligence Introduction" course generated with Qwen3.5-397B-A17B

export const CACHED_AI_COURSE = {
  stage: {
    id: 'demo-ai-intro',
    name: '人工智能导论',
    description: '从AI基础到前沿技术，系统掌握人工智能核心知识',
    style: 'professional',
    createdAt: 1721234567890,
    updatedAt: 1721234567890,
    interactiveMode: true,
    taskEngineMode: false,
    languageDirective:
      '本课程采用中文教学，专业术语保留英文原文（如 CNN、Transformer、RLHF），首次出现时给出中文解释。',
  },
  outlines: [
    {
      id: 'scene_1',
      type: 'slide',
      title: '课程介绍：人工智能导论',
      description: '欢迎来到《人工智能导论》！本课程将带你从AI历史走到最前沿的生成式AI。',
      keyPoints: [
        '课程名称：人工智能导论（10章，约40学时）',
        '目标受众：计算机科学本科生/零基础转行者',
        '学习目标：建立AI全栈知识体系，理解核心算法原理',
        '先修要求：Python基础、线性代数、概率论',
        '考核方式：章节测验(30%)+期中项目(30%)+期末项目(40%)',
      ],
      order: 1,
    },
    {
      id: 'scene_2',
      type: 'slide',
      title: '第1章：人工智能概述——什么是AI？',
      description: '从图灵测试到达特茅斯会议，追溯AI的诞生与三次浪潮。',
      keyPoints: [
        'AI定义：让机器表现出类人智能的科学',
        '图灵测试(1950)：判断机器是否能像人一样思考',
        '达特茅斯会议(1956) —— AI学科正式诞生',
        '三次浪潮：符号主义(1956-74) → 专家系统(1980-87) → 深度学习(2012-)',
        '三大流派：符号主义(逻辑推理) / 连接主义(神经网络) / 行为主义(强化学习)',
      ],
      order: 2,
    },
    {
      id: 'scene_3',
      type: 'quiz',
      title: '第1章测验：AI基础概念',
      description: '检验你对AI历史、定义、三大流派的理解。',
      keyPoints: ['AI定义', '达特茅斯会议', '三次浪潮', '三大流派区别'],
      order: 3,
      quizConfig: { questionCount: 3, difficulty: 'easy', questionTypes: ['single', 'multiple'] },
    },
    {
      id: 'scene_4',
      type: 'slide',
      title: '第2章：问题求解与搜索——A*算法',
      description: '从状态空间到启发式搜索，掌握经典A*算法原理与实现。',
      keyPoints: [
        '问题建模：初始状态、目标状态、动作、代价',
        '无信息搜索：BFS(最优但慢) / DFS(快但不完备) / UCS(代价最优)',
        '有信息搜索：A* = g(n) + h(n)，h(n)可采纳则保证最优',
        '启发式函数设计：曼哈顿距离、欧几里得距离、不相配瓦片数',
      ],
      order: 4,
    },
    {
      id: 'scene_5',
      type: 'interactive',
      title: 'A*算法可视化演练场',
      description: '在交互式网格中调整启发式函数，观察A*搜索路径变化。',
      keyPoints: [
        '拖拽设置起点/终点/障碍物',
        '切换启发式：曼哈顿 vs 欧几里得 vs 对角线',
        '实时显示open/closed集合、f/g/h值',
        '对比A* vs Dijkstra vs 贪心最佳优先搜索',
      ],
      order: 5,
      widgetType: 'visualization',
      widgetOutline: { visualizationType: 'pathfinding' },
    },
    {
      id: 'scene_6',
      type: 'slide',
      title: '第3章：知识表示与推理——专家系统',
      description: '从产生式规则到框架系统，看符号主义如何建模人类知识。',
      keyPoints: [
        '知识表示三要素：语法、语义、推理',
        '产生式系统：IF-THEN规则 + 工作内存 + 推理机',
        '语义网络：节点(概念) + 边(关系) + 继承机制',
        '框架系统：槽/默认值/过程附着 / Minsky帧理论',
        '专家系统架构：知识库 + 推理机 + 解释器 + 知识获取',
      ],
      order: 6,
    },
    {
      id: 'scene_7',
      type: 'quiz',
      title: '第2-3章测验：搜索与知识表示',
      description: '综合测验：无信息/有信息搜索、A*性质、知识表示方法对比。',
      keyPoints: ['BFS/DFS/UCS/A*复杂度', '启发式可采纳性/一致性', '产生式/语义网/框架区别'],
      order: 7,
      quizConfig: {
        questionCount: 4,
        difficulty: 'medium',
        questionTypes: ['single', 'multiple', 'short_answer'],
      },
    },
    {
      id: 'scene_8',
      type: 'slide',
      title: '第4章：机器学习基础——从线性回归到SVM',
      description: '监督学习核心：损失函数、正则化、核技巧、模型评估。',
      keyPoints: [
        '学习范式：监督/无监督/强化/半监督/自监督',
        '线性回归 → 逻辑回归(分类) → SVM(最大间隔/核技巧)',
        '决策树：信息增益/基尼指数 → 随机森林 → XGBoost/LightGBM',
        '过拟合对策：L1/L2正则化、Dropout、早停、数据增强、集成',
        '模型评估：准确率/精确率/召回率/F1/AUC-ROC、交叉验证',
      ],
      order: 8,
    },
    {
      id: 'scene_9',
      type: 'interactive',
      title: 'SVM决策边界可视化',
      description: '调整核函数(RBF/多项式/线性)与C参数，观察决策边界如何变化。',
      keyPoints: [
        '二维数据分布：线性可分 vs 非线性可分',
        '核函数映射到高维空间',
        'C参数控制间隔宽度 vs 错误容忍',
        '支持向量可视化',
      ],
      order: 9,
      widgetType: 'visualization',
      widgetOutline: { visualizationType: 'svm-boundary' },
    },
    {
      id: 'scene_10',
      type: 'slide',
      title: '第5章：神经网络与深度学习——从MLP到ResNet',
      description: '反向传播、卷积、残差连接，现代深度学习基石。',
      keyPoints: [
        '神经元：加权求和 + 激活函数(ReLU/Sigmoid/Tanh/GELU)',
        'MLP：全连接层 + 反向传播(链式法则) + 梯度下降',
        'CNN：卷积核/步长/填充/池化 —— 平移不变性',
        '经典架构：LeNet → AlexNet → VGG → ResNet(残差块/跳跃连接) → EfficientNet',
        'BatchNorm / LayerNorm / Dropout / 数据增强',
      ],
      order: 10,
    },
    {
      id: 'scene_11',
      type: 'interactive',
      title: 'CNN卷积操作演练场',
      description: '手动设置3x3卷积核，在输入图像上滑动观察特征图生成过程。',
      keyPoints: [
        '自定义卷积核：边缘检测/锐化/模糊/浮雕',
        '步长/填充/膨胀卷积对输出尺寸的影响',
        '特征图可视化：通道维度展示',
      ],
      order: 11,
      widgetType: 'code',
      widgetOutline: { language: 'python' },
    },
    {
      id: 'scene_12',
      type: 'slide',
      title: '第5章(续)：Transformer与大语言模型',
      description: '自注意力机制、位置编码、BERT/GPT架构差异。',
      keyPoints: [
        'Attention(Q,K,V) = softmax(QK^T/√d)V',
        '多头注意力：并行捕获不同子空间关系',
        '位置编码：正弦余弦/可学习/RoPE',
        'BERT(Encoder-only)：MLM + NSP → 理解任务',
        'GPT(Decoder-only)：自回归生成 → 生成任务',
        'Scaling Law：模型大小/数据量/计算量三要素',
      ],
      order: 12,
    },
    {
      id: 'scene_13',
      type: 'quiz',
      title: '第4-5章测验：机器学习与深度学习',
      description: 'SVM/决策树/集成、CNN/Transformer架构细节、Scaling Law。',
      keyPoints: ['核技巧原理', '残差块解决梯度消失', '多头注意力计算', 'BERT vs GPT预训练目标'],
      order: 13,
      quizConfig: {
        questionCount: 5,
        difficulty: 'hard',
        questionTypes: ['single', 'multiple', 'short_answer'],
      },
    },
    {
      id: 'scene_14',
      type: 'slide',
      title: '第6章：自然语言处理——从Word2Vec到LLM',
      description: '词向量、预训练微调、RLHF、RAG、In-Context Learning。',
      keyPoints: [
        '静态词向量：Word2Vec(CBOW/Skip-gram) / GloVe / FastText',
        '动态词向量：ELMo → BERT → GPT 系列',
        '预训练+微调范式：领域适配 / 少样本学习',
        'RLHF：Reward Model + PPO → 对齐人类偏好',
        'RAG：检索增强生成，解决幻觉与知识更新',
        'In-Context Learning：少样本提示，无需更新参数',
      ],
      order: 14,
    },
    {
      id: 'scene_15',
      type: 'interactive',
      title: 'RAG检索增强生成演练场',
      description: '上传文档 → 向量化存储 → 查询检索 → LLM生成答案，全流程可视化。',
      keyPoints: [
        '文档分块策略：固定长度/语义分块/递归分块',
        'Embedding模型对比：BGE / E5 / OpenAI text-embedding-3',
        '向量数据库：FAISS / Milvus / Chroma / Pinecone',
        '重排序：Cross-Encoder / Cohere Rerank',
        '生成引用溯源',
      ],
      order: 15,
      widgetType: 'code',
      widgetOutline: { language: 'python' },
    },
    {
      id: 'scene_16',
      type: 'slide',
      title: '第7章：计算机视觉——分类/检测/分割',
      description: '图像分类 → 目标检测(YOLO/Faster R-CNN) → 分割(U-Net/SAM)。',
      keyPoints: [
        '分类：ResNet/EfficientNet/ViT(Swin/DeiT)',
        '检测：两阶段(R-CNN系列) vs 一阶段(YOLO/SSD/RetinaNet)',
        'YOLO演进：v1→v8(Anchor-free/解耦头/任务对齐)',
        '分割：语义分割(FCN/DeepLab) / 实例分割(Mask R-CNN) / 全景分割',
        'SAM：Segment Anything Model，提示式分割',
      ],
      order: 16,
    },
    {
      id: 'scene_17',
      type: 'interactive',
      title: 'YOLOv8目标检测演练场',
      description: '上传图片/视频，实时运行YOLOv8，可调置信度阈值、NMS IoU阈值。',
      keyPoints: [
        '实时推理：ONNX Runtime / TensorRT 加速',
        '类别过滤 / 边界框可视化 / 关键点可视化',
        '导出ONNX/TensorRT/NCNN部署',
      ],
      order: 17,
      widgetType: 'code',
      widgetOutline: { language: 'python' },
    },
    {
      id: 'scene_18',
      type: 'slide',
      title: '第8章：强化学习——从Q-learning到AlphaGo',
      description: 'MDP、值迭代、策略梯度、Actor-Critic、PPO、AlphaGo Zero。',
      keyPoints: [
        'MDP五元组：S/A/P/R/γ，贝尔曼方程',
        '值迭代/策略迭代 → Q-learning(SARSA/DQN)',
        'DQN创新：Experience Replay + Target Network',
        '策略梯度：REINFORCE → Actor-Critic(A2C/A3C) → PPO',
        'AlphaGo：监督学习预训练 + RL微调 + MCTS',
        'AlphaGo Zero：纯自我对弈，无人类数据',
      ],
      order: 18,
    },
    {
      id: 'scene_19',
      type: 'interactive',
      title: 'GridWorld Q-learning演练场',
      description: '在网格世界中训练智能体，观察Q表收敛与策略可视化。',
      keyPoints: ['ε-greedy探索策略', '学习率α / 折扣因子γ 调节', '实时显示价值函数热力图'],
      order: 19,
      widgetType: 'visualization',
      widgetOutline: { visualizationType: 'rl-gridworld' },
    },
    {
      id: 'scene_20',
      type: 'slide',
      title: '第9章：生成式AI——GAN/VAE/扩散模型/LLM应用',
      description: '从生成对抗到扩散模型，RAG/Agent构建LLM应用。',
      keyPoints: [
        'GAN：生成器 vs 判别器，模式崩溃、WGAN-GP',
        'VAE：编码器-解码器 + KL散度正则化',
        '扩散模型：前向加噪 + 反向去噪(DDPM/DDIM/Score-based)',
        'Stable Diffusion：潜在空间扩散 + CLIP文本条件 + U-Net',
        'LLM应用范式：Prompt Engineering / RAG / Agent(工具调用/规划/记忆)',
        'LangChain / LangGraph / AutoGen / CrewAI 框架对比',
      ],
      order: 20,
    },
    {
      id: 'scene_21',
      type: 'interactive',
      title: 'Stable Diffusion生成演练场',
      description: '输入Prompt + Negative Prompt，调整Steps/CFG/Seed，生成图像。',
      keyPoints: [
        '文生图 / 图生图 / Inpainting / Outpainting / ControlNet',
        'LoRA微调：低秩适配，快速风格/角色迁移',
        'ComfyUI节点式工作流可视化',
      ],
      order: 21,
      widgetType: 'code',
      widgetOutline: { language: 'python' },
    },
    {
      id: 'scene_22',
      type: 'slide',
      title: '第10章：AI伦理与未来——对齐、AGI、具身智能',
      description: '算法偏见、隐私保护、可解释性、AI对齐、AGI时间线。',
      keyPoints: [
        '偏见来源：数据/标签/模型/部署，公平性指标',
        '隐私：差分隐私 / 联邦学习 / 安全多方计算',
        '可解释性：SHAP / LIME / Attention可视化 / 概念瓶颈',
        '对齐问题：外部/内部对齐、奖励黑客、欺骗性对齐',
        'AGI定义/时间线/风险：Yudkowsky/LeCun/Hinton不同观点',
        '具身智能：从数字世界走向物理世界(机器人/自动驾驶)',
      ],
      order: 22,
    },
    {
      id: 'scene_23',
      type: 'quiz',
      title: '第6-10章期末综合测验',
      description: 'NLP/CV/RL/生成式AI/伦理，综合考察核心概念与架构细节。',
      keyPoints: [
        'Transformer变体',
        'YOLO架构演进',
        'PPO裁剪机制',
        '扩散模型采样',
        'RLHF流程',
        'AI对齐核心难点',
      ],
      order: 23,
      quizConfig: {
        questionCount: 8,
        difficulty: 'hard',
        questionTypes: ['single', 'multiple', 'short_answer'],
      },
    },
    {
      id: 'scene_24',
      type: 'slide',
      title: '课程总结与学习路线图',
      description: '回顾十章核心知识，给出进阶学习路线与资源推荐。',
      keyPoints: [
        '核心回顾：搜索/知识表示 → ML/DL → NLP/CV/RL → 生成式AI → 伦理',
        '进阶方向：多模态大模型 / Agent系统 / 具身智能 / AI安全',
        '推荐资源：CS231n/CS224n/Spinning Up/Deep RL Bootcamp',
        '实战平台：Kaggle / Hugging Face / Papers With Code / ModelScope',
        '关键建议：动手跑通经典代码 > 只看论文；建立知识图谱 > 死记硬背',
      ],
      order: 24,
    } as const,
  ],
  // Pre-generated content for first few scenes (for instant preview)
  sceneContent: {
    scene_1: {
      elements: [
        {
          id: 'title_1',
          type: 'text',
          left: 60,
          top: 80,
          width: 880,
          height: 58,
          content:
            '<p style="font-size:32px; font-weight:bold; text-align:center;">课程介绍：人工智能导论</p>',
          defaultFontName: 'Microsoft YaHei',
          defaultColor: '#333333',
          rotate: 0,
        },
        {
          id: 'subtitle_1',
          type: 'text',
          left: 60,
          top: 148,
          width: 880,
          height: 58,
          content:
            '<p style="font-size:24px; text-align:center; color:#555555;">从AI基础到前沿技术，系统掌握人工智能核心知识</p>',
          defaultFontName: 'Microsoft YaHei',
          defaultColor: '#555555',
          rotate: 0,
        },
        {
          id: 'points_1',
          type: 'text',
          left: 80,
          top: 240,
          width: 840,
          height: 280,
          content:
            '<ul style="font-size:18px; line-height:2.2;"><li>课程名称：人工智能导论（10章，约40学时）</li><li>目标受众：计算机科学本科生 / 零基础转行者</li><li>学习目标：建立AI全栈知识体系，理解核心算法原理</li><li>先修要求：Python基础、线性代数、概率论</li><li>考核方式：章节测验(30%) + 期中项目(30%) + 期末项目(40%)</li></ul>',
          defaultFontName: 'Microsoft YaHei',
          defaultColor: '#333333',
          rotate: 0,
        },
      ],
      background: { type: 'solid', color: '#ffffff' },
    },
  },
  // Pre-generated actions for first scene
  sceneActions: {
    scene_1: {
      actions: [
        {
          id: 'speech_1',
          type: 'speech',
          text: '欢迎来到《人工智能导论》课程！我是你的AI助教，将陪伴你完成这10章的学习之旅。',
          speaker: 'assistant',
          audioId: 'tts_1',
        },
        {
          id: 'speech_2',
          type: 'speech',
          text: '本课程涵盖了从经典AI搜索算法，到现代深度学习、大语言模型、生成式AI，再到AI伦理与未来的完整知识体系。',
          speaker: 'assistant',
          audioId: 'tts_2',
        },
        {
          id: 'speech_3',
          type: 'speech',
          text: '无论你是计算机专业的学生，还是想转行AI的零基础学习者，都能在这里找到适合自己的学习路径。让我们开始吧！',
          speaker: 'assistant',
          audioId: 'tts_3',
        },
      ],
    },
  },
};

export type CachedCourse = typeof CACHED_AI_COURSE;
