blank_issues_enabled: false
contact_links:
  - name: Security Report
    url: https://gitcode.com/badhope/nova/security/advisories/new
    about: Report security vulnerabilities privately
  - name: Discussions
    url: https://gitcode.com/badhope/nova/discussions
    about: Ask questions and share ideas in Discussions
